### ISSUE TITLE
styx live/preview fails

### ISSUE THREAD

**Issue by sjmackenzie** [styx-static/styx#33] opened 2017-11-06 20:05 UTC
# steps to reproduce

* `$ styx new site site-name`
* `$ cd site-name`
* `$ styx live` or `$ styx preview`

# Expected behaviour
* the live feature works as documented in `$ styx --help`

# Actual behaviour
```
$ sudo styx live
[sudo] password for stewart: 
building path(s) ‘/nix/store/8zxrnqx2qywn09kj0n36bn4qxz1dm3pk-styx-0.7.0-lib’, ‘/nix/store/bddqgzrx0hv13rfpqq99bhc6flhyiyl1-styx-0.7.0’, ‘/nix/store/wbjz2v70bb8ajfc18n0p5361wva2yl22-styx-0.7.0-themes’
unpacking sources
unpacking source archive /nix/store/k6bpid8qjj9jnh27wcvjzvcblygc95sk-styx-src
source root is styx-src
chmod: changing permissions of 'styx-src': Operation not permitted
chmod: changing permissions of 'styx-src/LICENSE': Operation not permitted
chmod: changing permissions of 'styx-src/derivation.nix': Operation not permitted
chmod: changing permissions of 'styx-src/themes': Operation not permitted
...
chmod: changing permissions of 'styx-src/tests/data/meta.md': Operation not permitted
chmod: changing permissions of 'styx-src/tests/data/complex.md': Operation not permitted
chmod: changing permissions of 'styx-src/tests/default.nix': Operation not permitted
chmod: changing permissions of 'styx-src/release.nix': Operation not permitted
builder for ‘/nix/store/0h6vn6rn9s99ani0qqz8ql0glcfkd7yy-styx-0.7.0.drv’ failed with exit code 1
error: build of ‘/nix/store/0h6vn6rn9s99ani0qqz8ql0glcfkd7yy-styx-0.7.0.drv’ failed
---
Error: Site could not been built, fix the errors and run the command again.
The '--show-trace' flag can be used to show debug information.
```

**Comment by ericsagnes** [comment] 2017-11-07 12:17
That's weird, if styx is installed a `styx preview` should not trigger a new `styx-lib` build.  
Moreover the `chmod` operations on the source are done by nix so it's puzzling that these fails.

I tried to reproduce this bug but without success on NixOS with nix 1.11.13 and nix 1.11.15.
Is this happening Mac OS or some exotic platform?
Is there any more information that could help to reproduce?

Does things get any better by using styx from a nix-shell?

```
$ nix-shell -p styx -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz
```

**Comment by sjmackenzie** [comment] 2017-11-07 12:35
`$ nix-shell -p styx -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz`

The above command works well. Thanks.

These are my details:

```
$ nixos-version
18.03pre117327.3fe7cddc30 (Impala)

$ nix-env --version 
nix-env (Nix) 1.11.15

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion 
"18.03pre117327.3fe7cddc30"
```

**Comment by ericsagnes** [comment] 2017-11-07 13:50
mmm, couldn't reproduce with these versions too:

```
$ nix-shell -p styx nix -I nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/3fe7cddc30.tar.gz
$ styx new site foo && cd foo
$ styx preview
fetching path ‘/nix/store/5h0dx5q0dzkm6d8kbdr5flplb2rgmsd1-stdenv’...

*** Downloading ‘https://cache.nixos.org/nar/094pw1bxshvbmjfw2y50kxlrfyzm6bxzbflhh4r29rx2z2qzqn7i.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/5h0dx5q0dzkm6d8kbdr5flplb2rgmsd1-stdenv’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8368  100  8368    0     0   5054      0  0:00:01  0:00:01 --:--:--  5056

building path(s) ‘/nix/store/ivyg14kdgsq3827843gvjwrbal0z46b2-styx-0.7.0’, ‘/nix/store/si46k1vn8dwdpzkd0r7a8q6p043sh1i1-styx-0.7.0-themes’, ‘/nix/store/za2xkdxc7yz3inr2dv8lbpzi32gfj9iq-styx-0.7.0-lib’
unpacking sources
unpacking source archive /nix/store/xchrmaz7rychh7pmxykv67wd3s8dk66v-styx-src
source root is styx-src
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/ivyg14kdgsq3827843gvjwrbal0z46b2-styx-0.7.0
stripping (with flags -S) in /nix/store/ivyg14kdgsq3827843gvjwrbal0z46b2-styx-0.7.0/bin 
patching script interpreter paths in /nix/store/ivyg14kdgsq3827843gvjwrbal0z46b2-styx-0.7.0
checking for references to /tmp/nix-build-styx-0.7.0.drv-0 in /nix/store/ivyg14kdgsq3827843gvjwrbal0z46b2-styx-0.7.0...
shrinking RPATHs of ELF executables and libraries in /nix/store/za2xkdxc7yz3inr2dv8lbpzi32gfj9iq-styx-0.7.0-lib
patching script interpreter paths in /nix/store/za2xkdxc7yz3inr2dv8lbpzi32gfj9iq-styx-0.7.0-lib
checking for references to /tmp/nix-build-styx-0.7.0.drv-0 in /nix/store/za2xkdxc7yz3inr2dv8lbpzi32gfj9iq-styx-0.7.0-lib...
shrinking RPATHs of ELF executables and libraries in /nix/store/si46k1vn8dwdpzkd0r7a8q6p043sh1i1-styx-0.7.0-themes
patching script interpreter paths in /nix/store/si46k1vn8dwdpzkd0r7a8q6p043sh1i1-styx-0.7.0-themes
checking for references to /tmp/nix-build-styx-0.7.0.drv-0 in /nix/store/si46k1vn8dwdpzkd0r7a8q6p043sh1i1-styx-0.7.0-themes...
these derivations will be built:
  /nix/store/4jzsw6xkz6cpqhlfx8844igahm5s1gl8-styx-site.drv
building path(s) ‘/nix/store/j69mipd38sn3jjzf6fqcm09dx14a5vsz-styx-site’
server listening on http://127.0.0.1:8080
press Ctrl+C to stop
```

Note: `styx preview` indeed build a new styx lib when run the first time.

Anyway as I cannot reproduce and the `nix-shell` trick works, I am closing this for now.
Feel free to re-open if you want.

**Closed as completed by ericsagnes** 2017-11-07 13:50 UTC

**Comment by sjmackenzie** [comment] 2017-11-07 14:20
Okay, perfect!
